# -*- coding: utf-8 -*-

'''
Created on Apr 17, 2019

@author: Frank Feuerbacher
'''

import xbmcgui
from xbmcgui import (Control, ControlImage, ControlButton, ControlEdit,
                     ControlGroup, ControlLabel, ControlList, ControlTextBox,
                     ControlSpin, ControlSlider, ControlProgress, ControlFadeLabel,
                     ControlRadioButton)

from common.constants import Constants, Movie
from common.exceptions import AbortException
from common.imports import *
from common.logger import (LazyLogger, Trace)

module_logger = LazyLogger.get_addon_module_logger(file_path=__file__)


# noinspection Annotator
class LegalInfo(xbmcgui.WindowXML):
    """
        Page shown at startup displaying legal information, such as logos, etc.
    """

    _instance = None
    _destroyed = False
    _window_id: str = None

    @staticmethod
    def get_instance():
        # type: () -> LegalInfo
        """

        :return:
        """
        if LegalInfo._instance is None and not LegalInfo._destroyed:
            LegalInfo._instance = LegalInfo('legal.xml',
                                            Constants.ADDON_PATH, 'Default')
        return LegalInfo._instance

    def __init__(self, *args, **kwargs):
        # type: (...) ->  None
        """

        :param args:
        :param kwargs:
        """
        super().__init__(*args)
        self._logger = module_logger.getChild(type(self).__name__)
        LegalInfo._instance = self
        type(self)._window_id = xbmcgui.getCurrentWindowId()

    def onInit(self):
        # type: () -> None
        """

        :return:
        """

    def close(self):
        # type: () -> None
        """

        :return:
        """
        super().close()

    def destroy(self):
        # type: () -> None
        """

        :return:
        """
        del LegalInfo._instance
        LegalInfo._instance = None
        LegalInfo._destroyed = True

    def show(self):
        super().show()
        label: Union[ControlLabel, Control] = self.getControl(38021)
        label.setLabel('[B]Random Trailers is powered by:[/B]')

        TFH_NOTICE = 'DRAFT AGREEMENT\n' \
                     'Some of the content displayed originates from Trailers From Hell ' \
                     '(TFH) by a non-exclusive agreement.' \
                     'This agreement requires that this service is provided free of ' \
                     'charge and that no revenue is generated by this' \
                     'plugin or the displayed content. Trailers From Hell reserves the ' \
                     'right to change the terms of this agreement.' \
                     '\n\n' \
                     'Trailers From Hell. All Rights Reserved.\n' \
                     'All trailers appearing on TrailersFromHell.com are the property ' \
                     'of their respective owners.\n\n' \
                     'Trailers From Hell\n\n' \
                     '© 2007-2020'

        text_control: Union[Control, ControlTextBox] = self.getControl(38022)
        text_control.setText(TFH_NOTICE)
